### ISSUE TITLE
如何处理基本数据类型，比如发送String

### ISSUE THREAD

**Issue by jp1017** [SilenceDut/Router#1]
:question:

**Comment by SilenceDut** [comment]
类似这样Router.getInstance().getReceiver(AnyInterface.class).anyMethod(String str);
和EventBus不一样，不是以数据类型查找注册者的，所以任何基本类型都没关系。
Demo里有发送string的例子。 @jp1017

**Comment by jp1017** [comment]
Demo我看了，是这样发送的啊，如果发送String事件，没法搞？
