### ISSUE TITLE
receiverType must be a interface

### ISSUE THREAD

**Issue by jp1017** [SilenceDut/Router#2]
事件必须为接口啊

**Comment by SilenceDut** [comment]
接口只是用来区分是哪个注册者实现了这个接口。
像Demo里Router.getInstance().getReceiver(Event.MainView.class).textMainThread("main");
这句就是发送了"main"字符串，然后所有继承了Event.MainView接口实现的观察者的textMainThread都会接收到，如果还有问题，可加我QQ 3026354251
