### ISSUE TITLE
采用编译时处理注解？

### ISSUE THREAD

**Issue by kejunlu** [SilenceDut/Router#3]
发送消息时通过动态代理获取接收消息的方法，运用了反射获取了方法和注解，使用编译时处理注解貌似是多余的吧？并没有通过编译时提高性能，不知我是否理解错望解答

**Comment by SilenceDut** [comment]
其实编译时注解主要处理的是通过注解找到方法被回调的线程，当然没有使用也几乎不影响性能

**Comment by kejunlu** [comment]
已经通过动态代理拿到了接收消息的方法，同时method.getAnnotation(Subscribe.class)得到回调的线程，再使用编译时获取注解是否有些多余？
