### ISSUE TITLE
每次debug到接口那个地方就会崩溃，这个是框架原因吗！

### ISSUE THREAD

**Issue by zombiu** [SilenceDut/Router#6]

**Comment by qzqs** [comment]
我也出现这个问题，每次调试就会报错！

**Comment by zombiu** [comment]
> 我也出现这个问题，每次调试就会报错！

生成的Proxy不能debug！

**Comment by SilenceDut** [comment]
![image](https://user-images.githubusercontent.com/14820886/101564300-d8b63780-3a05-11eb-8c75-5df43f7be7ee.png)
我用的时候一般在这里断点，没出现过问题，这里可以得到所有信息
